language: node_js
node_js:
  - "6"
  - "7"
  - "8"
services:
  - mongodb
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
script:
  - npm test
